# oil: Oil  Raises error as "oil" is in "boiler" -> duplicate mappings
biomass: Biomass
biomass-biogas_plant: Biogas plant
biomass-shortage: Biomass shortage
biogas: Biogas
biogas-biogas_upgrading_plant: Biogas upgrading plant
biogas-shortage: Biogas shortage
biogas-bpchp_central: Biogas central CHP
biogas-bpchp_decentral: Biogas decentral CHP
ch4-boiler: CH4 boiler
ch4-bpchp_central: CH4 central CHP
ch4-bpchp_decentral: CH4 decentral CHP
ch4-extchp_central: CH4 central CCGT
ch4-extchp_decentral: CH4 decentral CCGT
ch4-gt: CH4 GT
ch4-import: CH4 import
electricity-bev_charging: BEV charging
electricity-demand_hh: El. demand HH
electricity-demand_cts: El. demand CTS
electricity-demand_ind: El. demand IND
electricity-electrolyzer: Electrolyzer
electricity-export: El. export
electricity-heatpump_central: Heat pump (DH)
electricity-heatpump_decentral: Heat pump (domestic)
electricity-import: El. import
electricity-large_scale_battery: Large-scale battery
electricity-small_scale_battery: Small-scale battery
electricity-pth: res. PtH
h2-bpchp_central: H2 central CHP
h2-bpchp_decentral: H2 decentral CHP
h2-extchp_central: H2 central CCGT
h2-extchp_decentral: H2 decentral CCGT
h2-cavern: H2 cavern
h2-demand: H2 demand
h2-excess: H2 excess
h2-gt: H2 GT
h2-import: H2 import
h2-shortage: H2 import
heat_central-demand_hh: Heat cen. demand HH
heat_central-demand_cts: Heat cen. demand CTS
heat_central-demand_ind: Heat cen. demand IND
heat_central-excess: Heat cen. excess
heat_central-storage: Heat cen. storage
heat_decentral-demand_hh: Heat dec. demand HH
heat_decentral-demand_cts: Heat dec. demand CTS
heat_decentral-demand_ind: Heat dec. demand IND
heat_decentral-excess: Heat dec. excess
heat_decentral-storage: Heat dec. storage
hydro-ror: Hydro ROR
solar-pv_ground: PV ground
solar-pv_rooftop: PV rooftop
solar-thermalcollector_central: Heat cen. solar thermal collector
solar-thermalcollector_decentral: Heat dec. solar thermal collector
wind-onshore: Wind on
wood-shortage: Wood shortage
wood-extchp_central: Wood central CHP
wood-extchp_decentral: Wood decentral CHP
lignite-shortage: Lignite shortage
