write_default_scalars:
  capacity_backpressure: {
    "var_name": "capacity",
    "type": backpressure,
    "tech": None,
    "which": "zeros",
    "var_unit": "MW",
  }
  capacity_conversion: {
    "var_name": "capacity",
    "type": conversion,
    "tech": None,
    "which": "zeros",
    "var_unit": "MW",
  }
  capacity_extraction: {
    "var_name": "capacity",
    "type": extraction,
    "tech": None,
    "which": "zeros",
    "var_unit": "MW",
  }
  capacity_storage: {
    "var_name": "capacity",
    "type": storage,
    "tech": None,
    "which": "zeros",
    "var_unit": "MW",
  }
  capacity_volatile: {
    "var_name": "capacity",
    "type": volatile,
    "tech": None,
    "which": "zeros",
    "var_unit": "MW",
  }
  capacity_shortage: {
    "var_name": "capacity",
    "type": shortage,
    "tech": None,
    "which": "high_capacity",
    "var_unit": "MW",
  }
  capacity_excess: {
    "var_name": "capacity",
    "type": excess,
    "tech": None,
    "which": "empty",
    "var_unit": "MW",
  }
  from_to_capacity_link: {
    "var_name": "from_to_capacity",
    "type": link,
    "tech": None,
    "which": "high_capacity",
    "var_unit": "MW",
  }
  to_from_capacity_link: {
    "var_name": "to_from_capacity",
    "type": link,
    "tech": None,
    "which": "high_capacity",
    "var_unit": "MW",
  }
  loss_link: {
    "var_name": "loss",
    "type": link,
    "tech": None,
    "which": "zeros",
    "var_unit": "None",
  }
  amount: {
    "var_name": "amount",
    "type": None,
    "tech": None,
    "which": "zeros",
    "var_unit": "MWh/a",
  }
  capacity_potential: {
    "var_name": "capacity_potential",
    "type": None,
    "tech": None,
    "which": "empty",
    "var_unit": "MW",
  }
  carrier_cost: {
    "var_name": "carrier_cost",
    "type": None,
    "tech": None,
    "which": "zeros",
    "var_unit": "Eur/MWh",
  }
  expandable: {
    "var_name": "expandable",
    "type": None,
    "tech": None,
    "which": "false",
    "var_unit": "None",
  }
  input_parameters_storage: {
    "var_name": "input_parameters",
    "type": storage,
    "tech": None,
    "which": "variable_costs",
    "var_unit": "None",
  }
  input_parameters: {
    "var_name": "input_parameters",
    "type": None,
    "tech": None,
    "which": "empty_dict",
    "var_unit": "None",
  }
  marginal_cost_volatile: {
    "var_name": "marginal_cost",
    "type": volatile,
    "tech": None,
    "which": "zeros",
    "var_unit": "EUR/MWh",
  }
  storage_capacity: {
    "var_name": "storage_capacity",
    "type": None,
    "tech": None,
    "which": "zeros",
    "var_unit": "MWh",
  }
  storage_capacity_potential: {
    "var_name": "storage_capacity_potential",
    "type": None,
    "tech": None,
    "which": "empty",
    "var_unit": "MWh",
  }
  emissions_not_modeled: {
    "var_name": "emissions_not_modeled",
    "type": None,
    "tech": None,
    "which": "emissions_not_modeled",
    "var_unit": "kg_CO2_eq/MWh",
  }
  emissions_1990: {
    "var_name": "emissions_1990",
    "type": None,
    "tech": None,
    "which": "zeros",
    "var_unit": "kg_CO2_eq/MWh",
  }
  emission_reduction_factor: {
    "var_name": "emission_reduction_factor",
    "type": None,
    "tech": None,
    "which": "emission_reduction_factor",
    "var_unit": "None",
  }
costs_efficiencies: [
    "capacity_cost_overnight",
    "condensing_efficiency",
    "efficiency",
    "electric_efficiency",
    "fixom_cost",
    "lifetime",
    "loss_rate",
    "marginal_cost",
    "storage_capacity_cost_overnight",
    "storage_fixom_cost",
    "thermal_efficiency",
    "wacc"
  ]
