##############################################################################
# This file holds configuration parameters for the creation of this dataset. #
##############################################################################

# Filter settings
attributes:
  {"EinheitMastrNummer": "mastr_id",
   "KwkMastrNummer": "kwk_mastr_id",
   "Kraftwerksnummer": "bnetza_id",
   "EinheitBetriebsstatus": "status",
   "LokationMastrNummer": "mastr_location_id",
   "Postleitzahl": "zip_code",
   "Ort": "city",
   "Laengengrad": "lon",
   "Breitengrad": "lat",
   "Inbetriebnahmedatum": "commissioning_date",
   "GeplantesInbetriebnahmedatum": "commissioning_date_planned",
   "DatumEndgueltigeStilllegung": "decommissioning_date",
   "NameKraftwerk": "name",
   "NameKraftwerksblock": "block_name",
   "Einsatzort": "usage_sector",
   "Nettonennleistung": "capacity_net",
   "Bruttoleistung": "capacity_gross",
   "ThermischeNutzleistung": "th_capacity",
   "Einspeisungsart": "feedin_type",
   "Technologie": "technology",
   "Hauptbrennstoff": "fuel_primary",
   "WeitererHauptbrennstoff": "fuel_secondary",
   "WeitereBrennstoffe": "fuel_other",
   "NetzbetreiberpruefungStatus": "validated_by_system_operator"}
attributes_filter:
  {"Land": "Deutschland",
   "EinheitBetriebsstatus": ["In Betrieb", "In Planung"],
   "Landkreis": ["Wittenberg", "Anhalt-Bitterfeld", "Dessau-Ro√ülau"]}

# Output settings
layer: bnetza_mastr_combustion
